/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "trace_streamer_config.h"
#include "memory_plugin_common.pbreader.h"
#include "memory_plugin_result.pbreader.h"
#include "log.h"
namespace SysTuning {
namespace TraceCfg {
using namespace ProtoReader;
TraceStreamerConfig::TraceStreamerConfig()
{
    InitEventNameMap();
    eventErrorDescMap_ = {
        {STAT_EVENT_RECEIVED, TRACE_STAT_TYPE_RECEIVED_DESC},
        {STAT_EVENT_DATA_LOST, TRACE_STAT_TYPE_LOST_DESC},
        {STAT_EVENT_NOTMATCH, TRACE_STAT_TYPE_NOTMATCH_DESC},
        {STAT_EVENT_NOTSUPPORTED, TRACE_STAT_TYPE_NOTSUPPORTED_DESC},
        {STAT_EVENT_DATA_INVALID, TRACE_STAT_TYPE_DATA_INVALID_DESC},
    };
    serverityLevelDescMap_ = {
        {STAT_SEVERITY_LEVEL_INFO, STAT_SEVERITY_LEVEL_INFO_DESC},
        {STAT_SEVERITY_LEVEL_WARN, STAT_SEVERITY_LEVEL_WARN_DESC},
        {STAT_SEVERITY_LEVEL_ERROR, STAT_SEVERITY_LEVEL_ERROR_DESC},
        {STAT_SEVERITY_LEVEL_FATAL, STAT_SEVERITY_LEVEL_FATAL_DESC},
    };
    memNameMap_ = {
        {MEM_VM_SIZE, MEM_INFO_VM_SIZE_DESC},   {MEM_VM_LOCKED, MEM_INFO_LOCKED_DESC},
        {MEM_VM_RSS, MEM_INFO_RSS_DESC},        {MEM_VM_ANON, MEM_INFO_RSS_ANON_DESC},
        {MEM_RSS_FILE, MEM_INFO_RSS_FILE_DESC}, {MEM_RSS_SHMEM, MEM_INFO_RSS_SCHEM_DESC},
        {MEM_VM_SWAP, MEM_INFO_SWAP_DESC},      {MEM_VM_LOCKED, MEM_INFO_VIRT_DESC},
        {MEM_VM_HWM, MEM_INFO_HWM_DESC},        {MEM_OOM_SCORE_ADJ, MEM_INFO_SCORE_ADJ_DESC},
        {MEM_PURG_SUM, MEM_INFO_PURG_SUM_DESC}, {MEM_PURG_PIN, MEM_INFO_PURG_PIN_DESC},
        {MEM_GL_PSS, MEM_INFO_GL_PSS_DESC},
    };

    InitSysMemMap();
    InitSysVmemMap();
    InitSecurityMap();
    if (eventNameMap_.size() != TRACE_EVENT_MAX) {
        TS_LOGF("eventNameMap_.size() max be %d, logic error", TRACE_EVENT_MAX);
    }
    if (eventErrorDescMap_.size() != STAT_EVENT_MAX) {
        TS_LOGF("eventErrorDescMap_.size() max be %d, logic error", STAT_EVENT_MAX);
    }
    if (serverityLevelDescMap_.size() != STAT_SEVERITY_LEVEL_MAX) {
        TS_LOGF("serverityLevelDescMap_.size() max be %d, logic error", STAT_SEVERITY_LEVEL_MAX);
    }
    if (eventParserStatSeverityDescMap_.size() != TRACE_EVENT_MAX) {
        TS_LOGF("eventParserStatSeverityDescMap_.size() max be %d, logic error", TRACE_EVENT_MAX);
    }
    if (memNameMap_.size() != MEM_MAX) {
        TS_LOGF("memNameMap_.size() max be %d, logic error", MEM_MAX);
    }
    for (int32_t i = TRACE_EVENT_START; i < TRACE_EVENT_MAX; i++) {
        if (eventParserStatSeverityDescMap_.at(static_cast<SupportedTraceEventType>(i)).size() != STAT_EVENT_MAX) {
            TS_LOGF("every item in eventParserStatSeverityDescMap_ max be %d, logic error", STAT_EVENT_MAX);
        }
    }
}

void TraceStreamerConfig::PrintInfo() const
{
    printf("---all kind of trace event info---\n");
    for (auto itor = eventNameMap_.begin(); itor != eventNameMap_.end(); itor++) {
        printf("%s\n", itor->second.c_str());
    }
    printf("\n");
    printf("---subdir of process mem info---\n");
    for (auto itor = memNameMap_.begin(); itor != memNameMap_.end(); itor++) {
        printf("%s\n", itor->second.c_str());
    }
    printf("\n");
    printf("---subdir of sys mem info---\n");
    for (auto itor = sysMemNameMap_.begin(); itor != sysMemNameMap_.end(); itor++) {
        printf("%s\n", itor->second.c_str());
    }
    printf("\n");
    printf("---subdir of sys vmem info---\n");
    for (auto itor = sysVirtualMemNameMap_.begin(); itor != sysVirtualMemNameMap_.end(); itor++) {
        printf("%s\n", itor->second.c_str());
    }
    printf("\n");
}

void TraceStreamerConfig::InitEventNameMap()
{
    eventNameMap_ = {{TRACE_EVENT_BINDER_TRANSACTION, TRACE_ACTION_BINDER_TRANSACTION},
                     {TRACE_EVENT_BINDER_TRANSACTION_RECEIVED, TRACE_ACTION_BINDER_TRANSACTION_RECEIVED},
                     {TRACE_EVENT_BINDER_TRANSACTION_ALLOC_BUF, TRACE_ACTION_BINDER_TRANSACTION_ALLOC_BUF},
                     {TRACE_EVENT_BINDER_TRANSACTION_LOCK, TRACE_ACTION_BINDER_TRANSACTION_LOCK},
                     {TRACE_EVENT_BINDER_TRANSACTION_LOCKED, TRACE_ACTION_BINDER_TRANSACTION_LOCKED},
                     {TRACE_EVENT_BINDER_TRANSACTION_UNLOCK, TRACE_ACTION_BINDER_TRANSACTION_UNLOCK},
                     {TRACE_EVENT_SCHED_SWITCH, TRACE_ACTION_SCHED_SWITCH},
                     {TRACE_EVENT_SCHED_BLOCKED_REASON, TRACE_ACTION_SCHED_BLOCKED_REASON},
                     {TRACE_EVENT_TASK_RENAME, TRACE_ACTION_TASK_RENAME},
                     {TRACE_EVENT_TASK_NEWTASK, TRACE_ACTION_TASK_NEWTASK},
                     {TRACE_EVENT_TRACING_MARK_WRITE, TRACE_ACTION_TRACING_MARK_WRITE},
                     {TRACE_EVENT_PRINT, TRACE_ACTION_PRINT},
                     {TRACE_EVENT_SCHED_WAKEUP, TRACE_ACTION_SCHED_WAKEUP},
                     {TRACE_EVENT_SCHED_WAKING, TRACE_ACTION_SCHED_WAKING},
                     {TRACE_EVENT_CPU_IDLE, TRACE_ACTION_CPU_IDLE},
                     {TRACE_EVENT_CPU_FREQUENCY, TRACE_ACTION_CPU_FREQUENCY},
                     {TRACE_EVENT_CPU_FREQUENCY_LIMITS, TRACE_ACTION_CPU_FREQUENCY_LIMITS},
                     {TRACE_EVENT_SUSPEND_RESUME, TRACE_ACTION_SUSPEND_RESUME},
                     {TRACE_EVENT_WORKQUEUE_EXECUTE_START, TRACE_ACTION_WORKQUEUE_EXECUTE_START},
                     {TRACE_EVENT_WORKQUEUE_EXECUTE_END, TRACE_ACTION_WORKQUEUE_EXECUTE_END},
                     {TRACE_EVENT_CLOCK_SET_RATE, TRACE_ACTION_CLOCK_SET_RATE},
                     {TRACE_EVENT_CLOCK_ENABLE, TRACE_ACTION_CLOCK_ENABLE},
                     {TRACE_EVENT_CLOCK_DISABLE, TRACE_ACTION_CLOCK_DISABLE},
                     {TRACE_EVENT_CLK_SET_RATE, TRACE_ACTION_CLK_SET_RATE},
                     {TRACE_EVENT_CLK_ENABLE, TRACE_ACTION_CLK_ENABLE},
                     {TRACE_EVENT_CLK_DISABLE, TRACE_ACTION_CLK_DISABLE},
                     {TRACE_EVENT_SYS_ENTRY, TRACE_ACTION_SYS_ENTRY},
                     {TRACE_EVENT_SYS_EXIT, TRACE_ACTION_SYS_EXIT},
                     {TRACE_EVENT_OOM_SCORE_ADJ_UPDATE, TRACE_ACTION_OOM_SCORE_ADJ_UPDATE},
                     {TRACE_EVENT_REGULATOR_SET_VOLTAGE, TRACE_ACTION_REGULATOR_SET_VOLTAGE},
                     {TRACE_EVENT_REGULATOR_SET_VOLTAGE_COMPLETE, TRACE_ACTION_REGULATOR_SET_VOLTAGE_COMPLETE},
                     {TRACE_EVENT_REGULATOR_DISABLE, TRACE_ACTION_REGULATOR_DISABLE},
                     {TRACE_EVENT_REGULATOR_DISABLE_COMPLETE, TRACE_ACTION_REGULATOR_DISABLE_COMPLETE},
                     {TRACE_EVENT_IPI_ENTRY, TRACE_ACTION_IPI_ENTRY},
                     {TRACE_EVENT_IPI_EXIT, TRACE_ACTION_IPI_EXIT},
                     {TRACE_EVENT_IRQ_HANDLER_ENTRY, TRACE_ACTION_IRQ_HANDLER_ENTRY},
                     {TRACE_EVENT_IRQ_HANDLER_EXIT, TRACE_ACTION_IRQ_HANDLER_EXIT},
                     {TRACE_EVENT_SOFTIRQ_RAISE, TRACE_ACTION_SOFTIRQ_RAISE},
                     {TRACE_EVENT_SOFTIRQ_ENTRY, TRACE_ACTION_SOFTIRQ_ENTRY},
                     {TRACE_EVENT_SOFTIRQ_EXIT, TRACE_ACTION_SOFTIRQ_EXIT},
                     {TRACE_EVENT_SCHED_WAKEUP_NEW, TRACE_ACTION_SCHED_WAKEUP_NEW},
                     {TRACE_EVENT_PROCESS_EXIT, TRACE_ACTION_PROCESS_EXIT},
                     {TRACE_EVENT_PROCESS_FREE, TRACE_ACTION_PROCESS_FREE},
                     {TRACE_EVENT_CLOCK_SYNC, TRACE_ACTION_CLOCK_SYNC},
                     {TRACE_EVENT_SIGNAL_GENERATE, TRACE_ACTION_SIGNAL_GENERATE},
                     {TRACE_EVENT_SIGNAL_DELIVER, TRACE_ACTION_SIGNAL_DELIVER},
                     {TRACE_EVENT_BLOCK_BIO_BACKMERGE, TRACE_ACTION_BLOCK_BIO_BACKMERGE},
                     {TRACE_EVENT_BLOCK_BIO_BOUNCE, TRACE_ACTION_BLOCK_BIO_BOUNCE},
                     {TRACE_EVENT_BLOCK_BIO_COMPLETE, TRACE_ACTION_BLOCK_BIO_COMPLETE},
                     {TRACE_EVENT_BLOCK_BIO_FRONTMERGE, TRACE_ACTION_BLOCK_BIO_FRONTMERGE},
                     {TRACE_EVENT_BLOCK_BIO_QUEUE, TRACE_ACTION_BLOCK_BIO_QUEUE},
                     {TRACE_EVENT_BLOCK_BIO_REMAP, TRACE_ACTION_BLOCK_BIO_REMAP},
                     {TRACE_EVENT_BLOCK_DIRTY_BUFFER, TRACE_ACTION_BLOCK_DIRTY_BUFFER},
                     {TRACE_EVENT_BLOCK_GETRQ, TRACE_ACTION_BLOCK_GETRQ},
                     {TRACE_EVENT_BLOCK_PLUG, TRACE_ACTION_BLOCK_PLUG},
                     {TRACE_EVENT_BLOCK_RQ_COMPLETE, TRACE_ACTION_BLOCK_RQ_COMPLETE},
                     {TRACE_EVENT_BLOCK_RQ_INSERT, TRACE_ACTION_BLOCK_RQ_INSERT},
                     {TRACE_EVENT_BLOCK_RQ_REMAP, TRACE_ACTION_BLOCK_RQ_REMAP},
                     {TRACE_EVENT_BLOCK_RQ_ISSUE, TRACE_ACTION_BLOCK_RQ_ISSUE},
                     {TRACE_EVENT_OTHER, TRACE_ACTION_OTHER},
                     {TRACE_MEMORY, TRACE_ACTION_MEMORY},
                     {TRACE_SYS_MEMORY, TRACE_ACTION_SYS_MEMORY},
                     {TRACE_SYS_VIRTUAL_MEMORY, TRACE_ACTION_SYS_VIRTUAL_MEMORY},
                     {TRACE_DISKIO, TRACE_ACTION_DISKIO},
                     {TRACE_PROCESS, TRACE_ACTION_PROCESS},
                     {TRACE_CPU_USAGE, TRACE_ACTION_CPU_USAGE},
                     {TRACE_NETWORK, TRACE_ACTION_NETWORK},
                     {TRACE_JS_MEMORY, TRACE_ACTION_JS_MEMORY},
                     {TRACE_PERF, TRACE_ACTION_PERF},
                     {TRACE_HILOG, TRACE_ACTION_HILOG},
                     {TRACE_HIDUMP_FPS, TRACE_ACTION_HIDUMP_FPS},
                     {TRACE_NATIVE_HOOK_MALLOC, TRACE_ACTION_NATIVE_HOOK_MALLOC},
                     {TRACE_NATIVE_HOOK_FREE, TRACE_ACTION_NATIVE_HOOK_FREE},
                     {TRACE_NATIVE_HOOK_MMAP, TRACE_ACTION_NATIVE_HOOK_MMAP},
                     {TRACE_NATIVE_HOOK_MUNMAP, TRACE_ACTION_NATIVE_HOOK_MUNMAP},
                     {TRACE_NATIVE_HOOK_RECORD_STATISTICS, TRACE_ACTION_NATIVE_HOOK_RECORD_STATISTICS},
                     {TRACE_NATIVE_HOOK_MEMTAG, TRACE_ACTION_NATIVE_HOOK_MEMTAG},
                     {TRACE_HISYSEVENT, TRACE_ACTION_HISYS_EVENT},
                     {TRACE_SMAPS, TRACE_ACTION_SMAPS},
                     {TRACE_ASHMEM, TRACE_ACTION_ASHMEM},
                     {TRACE_DMAMEM, TRACE_ACTION_DMAMEM},
                     {TRACE_GPU_PROCESS_MEM, TRACE_ACTION_GPU_PROCESS_MEM},
                     {TRACE_GPU_WINDOW_MEM, TRACE_ACTION_GPU_WINDOW_MEM},
                     {TRACE_VSYNC, TRACE_ACTION_VSYNC},
                     {TRACE_ONVSYNC, TRACE_ACTION_ONVSYNC},
                     {TRACE_FRAMEQUEUE, TRACE_ACTION_FRAMEQUEUE},
                     {TRACE_EVENT_EBPF, TRACE_ACTION_EBPF},
                     {TRACE_EVENT_EBPF_FILE_SYSTEM, TRACE_ACTION_EBPF_FILE_SYSTEM},
                     {TRACE_EVENT_EBPF_PAGED_MEMORY, TRACE_ACTION_EBPF_PAGED_MEMORY},
                     {TRACE_EVENT_EBPF_BIO_LATENCY, TRACE_ACTION_EBPF_BIO_LATENCY}};
}
void TraceStreamerConfig::InitSysMemMap()
{
    sysMemNameMap_ = {{SysMeminfoType::PMEM_UNSPECIFIED, SYS_MEMINFO_UNSPECIFIED_DESC},
                      {SysMeminfoType::PMEM_MEM_TOTAL, SYS_MEMINFO_MEM_TOTAL_DESC},
                      {SysMeminfoType::PMEM_MEM_FREE, SYS_MEMINFO_MEM_FREE_DESC},
                      {SysMeminfoType::PMEM_MEM_AVAILABLE, SYS_MEMINFO_MEM_AVAILABLE_DESC},
                      {SysMeminfoType::PMEM_BUFFERS, SYS_MEMINFO_BUFFERS_DESC},
                      {SysMeminfoType::PMEM_CACHED, SYS_MEMINFO_CACHED_DESC},
                      {SysMeminfoType::PMEM_SWAP_CACHED, SYS_MEMINFO_SWAP_CACHED_DESC},
                      {SysMeminfoType::PMEM_ACTIVE, SYS_MEMINFO_ACTIVE_DESC},
                      {SysMeminfoType::PMEM_INACTIVE, SYS_MEMINFO_INACTIVE_DESC},
                      {SysMeminfoType::PMEM_ACTIVE_ANON, SYS_MEMINFO_ACTIVE_ANON_DESC},
                      {SysMeminfoType::PMEM_INACTIVE_ANON, SYS_MEMINFO_INACTIVE_ANON_DESC},
                      {SysMeminfoType::PMEM_ACTIVE_FILE, SYS_MEMINFO_ACTIVE_FILE_DESC},
                      {SysMeminfoType::PMEM_INACTIVE_FILE, SYS_MEMINFO_INACTIVE_FILE_DESC},
                      {SysMeminfoType::PMEM_UNEVICTABLE, SYS_MEMINFO_UNEVICTABLE_DESC},
                      {SysMeminfoType::PMEM_MLOCKED, SYS_MEMINFO_MLOCKED_DESC},
                      {SysMeminfoType::PMEM_SWAP_TOTAL, SYS_MEMINFO_SWAP_TOTAL_DESC},
                      {SysMeminfoType::PMEM_SWAP_FREE, SYS_MEMINFO_SWAP_FREE_DESC},
                      {SysMeminfoType::PMEM_DIRTY, SYS_MEMINFO_DIRTY_DESC},
                      {SysMeminfoType::PMEM_WRITEBACK, SYS_MEMINFO_WRITEBACK_DESC},
                      {SysMeminfoType::PMEM_ANON_PAGES, SYS_MEMINFO_ANON_PAGES_DESC},
                      {SysMeminfoType::PMEM_MAPPED, SYS_MEMINFO_MAPPED_DESC},
                      {SysMeminfoType::PMEM_SHMEM, SYS_MEMINFO_SHMEM_DESC},
                      {SysMeminfoType::PMEM_SLAB, SYS_MEMINFO_SLAB_DESC},
                      {SysMeminfoType::PMEM_SLAB_RECLAIMABLE, SYS_MEMINFO_SLAB_RECLAIMABLE_DESC},
                      {SysMeminfoType::PMEM_SLAB_UNRECLAIMABLE, SYS_MEMINFO_SLAB_UNRECLAIMABLE_DESC},
                      {SysMeminfoType::PMEM_KERNEL_STACK, SYS_MEMINFO_KERNEL_STACK_DESC},
                      {SysMeminfoType::PMEM_PAGE_TABLES, SYS_MEMINFO_PAGE_TABLES_DESC},
                      {SysMeminfoType::PMEM_COMMIT_LIMIT, SYS_MEMINFO_COMMIT_LIMIT_DESC},
                      {SysMeminfoType::PMEM_COMMITED_AS, SYS_MEMINFO_COMMITED_AS_DESC},
                      {SysMeminfoType::PMEM_VMALLOC_TOTAL, SYS_MEMINFO_VMALLOC_TOTAL_DESC},
                      {SysMeminfoType::PMEM_VMALLOC_USED, SYS_MEMINFO_VMALLOC_USED_DESC},
                      {SysMeminfoType::PMEM_VMALLOC_CHUNK, SYS_MEMINFO_VMALLOC_CHUNK_DESC},
                      {SysMeminfoType::PMEM_CMA_TOTAL, SYS_MEMINFO_CMA_TOTAL_DESC},
                      {SysMeminfoType::PMEM_CMA_FREE, SYS_MEMINFO_CMA_FREE_DESC},
                      {SysMeminfoType::PMEM_KERNEL_RECLAIMABLE, SYS_MEMINFO_KERNEL_RECLAIMABLE_DESC},
                      {SysMeminfoType::PMEM_ACTIVE_PURG, SYS_MEMINFO_ACTIVE_PURG_DESC},
                      {SysMeminfoType::PMEM_INACTIVE_PURG, SYS_MEMINFO_INACTIVE_PURG_DESC},
                      {SysMeminfoType::PMEM_PINED_PURG, SYS_MEMINFO_PINED_PURG_DESC}};
}

void TraceStreamerConfig::InitSysVmemMap()
{
    sysVirtualMemNameMap_ = {
        {SysVMeminfoType::VMEMINFO_UNSPECIFIED, SYS_VMEMINFO_UNSPECIFIED_DESC},
        {SysVMeminfoType::VMEMINFO_NR_FREE_PAGES, SYS_VMEMINFO_NR_FREE_PAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ALLOC_BATCH, SYS_VMEMINFO_NR_ALLOC_BATCH_DESC},
        {SysVMeminfoType::VMEMINFO_NR_INACTIVE_ANON, SYS_VMEMINFO_NR_INACTIVE_ANON_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ACTIVE_ANON, SYS_VMEMINFO_NR_ACTIVE_ANON_DESC},
        {SysVMeminfoType::VMEMINFO_NR_INACTIVE_FILE, SYS_VMEMINFO_NR_INACTIVE_FILE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ACTIVE_FILE, SYS_VMEMINFO_NR_ACTIVE_FILE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_UNEVICTABLE, SYS_VMEMINFO_NR_UNEVICTABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_MLOCK, SYS_VMEMINFO_NR_MLOCK_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ANON_PAGES, SYS_VMEMINFO_NR_ANON_PAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_MAPPED, SYS_VMEMINFO_NR_MAPPED_DESC},
        {SysVMeminfoType::VMEMINFO_NR_FILE_PAGES, SYS_VMEMINFO_NR_FILE_PAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_DIRTY, SYS_VMEMINFO_NR_DIRTY_DESC},
        {SysVMeminfoType::VMEMINFO_NR_WRITEBACK, SYS_VMEMINFO_NR_WRITEBACK_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SLAB_RECLAIMABLE, SYS_VMEMINFO_NR_SLAB_RECLAIMABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SLAB_UNRECLAIMABLE, SYS_VMEMINFO_NR_SLAB_UNRECLAIMABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_PAGE_TABLE_PAGES, SYS_VMEMINFO_NR_PAGE_TABLE_PAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_KERNEL_STACK, SYS_VMEMINFO_NR_KERNEL_STACK_DESC},
        {SysVMeminfoType::VMEMINFO_NR_OVERHEAD, SYS_VMEMINFO_NR_OVERHEAD_DESC},
        {SysVMeminfoType::VMEMINFO_NR_UNSTABLE, SYS_VMEMINFO_NR_UNSTABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_BOUNCE, SYS_VMEMINFO_NR_BOUNCE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_VMSCAN_WRITE, SYS_VMEMINFO_NR_VMSCAN_WRITE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_VMSCAN_IMMEDIATE_RECLAIM, SYS_VMEMINFO_NR_VMSCAN_IMMEDIATE_RECLAIM_DESC},
        {SysVMeminfoType::VMEMINFO_NR_WRITEBACK_TEMP, SYS_VMEMINFO_NR_WRITEBACK_TEMP_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ISOLATED_ANON, SYS_VMEMINFO_NR_ISOLATED_ANON_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ISOLATED_FILE, SYS_VMEMINFO_NR_ISOLATED_FILE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SHMEM, SYS_VMEMINFO_NR_SHMEM_DESC},
        {SysVMeminfoType::VMEMINFO_NR_DIRTIED, SYS_VMEMINFO_NR_DIRTIED_DESC},
        {SysVMeminfoType::VMEMINFO_NR_WRITTEN, SYS_VMEMINFO_NR_WRITTEN_DESC},
        {SysVMeminfoType::VMEMINFO_NR_PAGES_SCANNED, SYS_VMEMINFO_NR_PAGES_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_WORKINGSET_REFAULT, SYS_VMEMINFO_WORKINGSET_REFAULT_DESC},
        {SysVMeminfoType::VMEMINFO_WORKINGSET_ACTIVATE, SYS_VMEMINFO_WORKINGSET_ACTIVATE_DESC},
        {SysVMeminfoType::VMEMINFO_WORKINGSET_NODERECLAIM, SYS_VMEMINFO_WORKINGSET_NODERECLAIM_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ANON_TRANSPARENT_HUGEPAGES, SYS_VMEMINFO_NR_ANON_TRANSPARENT_HUGEPAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_FREE_CMA, SYS_VMEMINFO_NR_FREE_CMA_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SWAPCACHE, SYS_VMEMINFO_NR_SWAPCACHE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_DIRTY_THRESHOLD, SYS_VMEMINFO_NR_DIRTY_THRESHOLD_DESC},
        {SysVMeminfoType::VMEMINFO_NR_DIRTY_BACKGROUND_THRESHOLD, SYS_VMEMINFO_NR_DIRTY_BACKGROUND_THRESHOLD_DESC},
        {SysVMeminfoType::VMEMINFO_PGPGIN, SYS_VMEMINFO_PGPGIN_DESC},
        {SysVMeminfoType::VMEMINFO_PGPGOUT, SYS_VMEMINFO_PGPGOUT_DESC},
        {SysVMeminfoType::VMEMINFO_PGPGOUTCLEAN, SYS_VMEMINFO_PGPGOUTCLEAN_DESC},
        {SysVMeminfoType::VMEMINFO_PSWPIN, SYS_VMEMINFO_PSWPIN_DESC},
        {SysVMeminfoType::VMEMINFO_PSWPOUT, SYS_VMEMINFO_PSWPOUT_DESC},
        {SysVMeminfoType::VMEMINFO_PGALLOC_DMA, SYS_VMEMINFO_PGALLOC_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGALLOC_NORMAL, SYS_VMEMINFO_PGALLOC_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGALLOC_MOVABLE, SYS_VMEMINFO_PGALLOC_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGFREE, SYS_VMEMINFO_PGFREE_DESC},
        {SysVMeminfoType::VMEMINFO_PGACTIVATE, SYS_VMEMINFO_PGACTIVATE_DESC},
        {SysVMeminfoType::VMEMINFO_PGDEACTIVATE, SYS_VMEMINFO_PGDEACTIVATE_DESC},
        {SysVMeminfoType::VMEMINFO_PGFAULT, SYS_VMEMINFO_PGFAULT_DESC},
        {SysVMeminfoType::VMEMINFO_PGMAJFAULT, SYS_VMEMINFO_PGMAJFAULT_DESC},
        {SysVMeminfoType::VMEMINFO_PGREFILL_DMA, SYS_VMEMINFO_PGREFILL_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGREFILL_NORMAL, SYS_VMEMINFO_PGREFILL_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGREFILL_MOVABLE, SYS_VMEMINFO_PGREFILL_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_KSWAPD_DMA, SYS_VMEMINFO_PGSTEAL_KSWAPD_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_KSWAPD_NORMAL, SYS_VMEMINFO_PGSTEAL_KSWAPD_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_KSWAPD_MOVABLE, SYS_VMEMINFO_PGSTEAL_KSWAPD_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_DIRECT_DMA, SYS_VMEMINFO_PGSTEAL_DIRECT_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_DIRECT_NORMAL, SYS_VMEMINFO_PGSTEAL_DIRECT_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_DIRECT_MOVABLE, SYS_VMEMINFO_PGSTEAL_DIRECT_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_KSWAPD_DMA, SYS_VMEMINFO_PGSCAN_KSWAPD_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_KSWAPD_NORMAL, SYS_VMEMINFO_PGSCAN_KSWAPD_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_KSWAPD_MOVABLE, SYS_VMEMINFO_PGSCAN_KSWAPD_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_DIRECT_DMA, SYS_VMEMINFO_PGSCAN_DIRECT_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_DIRECT_NORMAL, SYS_VMEMINFO_PGSCAN_DIRECT_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_DIRECT_MOVABLE, SYS_VMEMINFO_PGSCAN_DIRECT_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_DIRECT_THROTTLE, SYS_VMEMINFO_PGSCAN_DIRECT_THROTTLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGINODESTEAL, SYS_VMEMINFO_PGINODESTEAL_DESC},
        {SysVMeminfoType::VMEMINFO_SLABS_SCANNED, SYS_VMEMINFO_SLABS_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_KSWAPD_INODESTEAL, SYS_VMEMINFO_KSWAPD_INODESTEAL_DESC},
        {SysVMeminfoType::VMEMINFO_KSWAPD_LOW_WMARK_HIT_QUICKLY, SYS_VMEMINFO_KSWAPD_LOW_WMARK_HIT_QUICKLY_DESC},
        {SysVMeminfoType::VMEMINFO_KSWAPD_HIGH_WMARK_HIT_QUICKLY, SYS_VMEMINFO_KSWAPD_HIGH_WMARK_HIT_QUICKLY_DESC},
        {SysVMeminfoType::VMEMINFO_PAGEOUTRUN, SYS_VMEMINFO_PAGEOUTRUN_DESC},
        {SysVMeminfoType::VMEMINFO_ALLOCSTALL, SYS_VMEMINFO_ALLOCSTALL_DESC},
        {SysVMeminfoType::VMEMINFO_PGROTATED, SYS_VMEMINFO_PGROTATED_DESC},
        {SysVMeminfoType::VMEMINFO_DROP_PAGECACHE, SYS_VMEMINFO_DROP_PAGECACHE_DESC},
        {SysVMeminfoType::VMEMINFO_DROP_SLAB, SYS_VMEMINFO_DROP_SLAB_DESC},
        {SysVMeminfoType::VMEMINFO_PGMIGRATE_SUCCESS, SYS_VMEMINFO_PGMIGRATE_SUCCESS_DESC},
        {SysVMeminfoType::VMEMINFO_PGMIGRATE_FAIL, SYS_VMEMINFO_PGMIGRATE_FAIL_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_MIGRATE_SCANNED, SYS_VMEMINFO_COMPACT_MIGRATE_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_FREE_SCANNED, SYS_VMEMINFO_COMPACT_FREE_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_ISOLATED, SYS_VMEMINFO_COMPACT_ISOLATED_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_STALL, SYS_VMEMINFO_COMPACT_STALL_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_FAIL, SYS_VMEMINFO_COMPACT_FAIL_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_SUCCESS, SYS_VMEMINFO_COMPACT_SUCCESS_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_DAEMON_WAKE, SYS_VMEMINFO_COMPACT_DAEMON_WAKE_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_CULLED, SYS_VMEMINFO_UNEVICTABLE_PGS_CULLED_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_SCANNED, SYS_VMEMINFO_UNEVICTABLE_PGS_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_RESCUED, SYS_VMEMINFO_UNEVICTABLE_PGS_RESCUED_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_MLOCKED, SYS_VMEMINFO_UNEVICTABLE_PGS_MLOCKED_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_MUNLOCKED, SYS_VMEMINFO_UNEVICTABLE_PGS_MUNLOCKED_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_CLEARED, SYS_VMEMINFO_UNEVICTABLE_PGS_CLEARED_DESC},
        {SysVMeminfoType::VMEMINFO_UNEVICTABLE_PGS_STRANDED, SYS_VMEMINFO_UNEVICTABLE_PGS_STRANDED_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZSPAGES, SYS_VMEMINFO_NR_ZSPAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ION_HEAP, SYS_VMEMINFO_NR_ION_HEAP_DESC},
        {SysVMeminfoType::VMEMINFO_NR_GPU_HEAP, SYS_VMEMINFO_NR_GPU_HEAP_DESC},
        {SysVMeminfoType::VMEMINFO_ALLOCSTALL_DMA, SYS_VMEMINFO_ALLOCSTALL_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_ALLOCSTALL_MOVABLE, SYS_VMEMINFO_ALLOCSTALL_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_ALLOCSTALL_NORMAL, SYS_VMEMINFO_ALLOCSTALL_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_DAEMON_FREE_SCANNED, SYS_VMEMINFO_COMPACT_DAEMON_FREE_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_COMPACT_DAEMON_MIGRATE_SCANNED, SYS_VMEMINFO_COMPACT_DAEMON_MIGRATE_SCANNED_DESC},
        {SysVMeminfoType::VMEMINFO_NR_FASTRPC, SYS_VMEMINFO_NR_FASTRPC_DESC},
        {SysVMeminfoType::VMEMINFO_NR_INDIRECTLY_RECLAIMABLE, SYS_VMEMINFO_NR_INDIRECTLY_RECLAIMABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ION_HEAP_POOL, SYS_VMEMINFO_NR_ION_HEAP_POOL_DESC},
        {SysVMeminfoType::VMEMINFO_NR_KERNEL_MISC_RECLAIMABLE, SYS_VMEMINFO_NR_KERNEL_MISC_RECLAIMABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SHADOW_CALL_STACK_BYTES, SYS_VMEMINFO_NR_SHADOW_CALL_STACK_BYTES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SHMEM_HUGEPAGES, SYS_VMEMINFO_NR_SHMEM_HUGEPAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_SHMEM_PMDMAPPED, SYS_VMEMINFO_NR_SHMEM_PMDMAPPED_DESC},
        {SysVMeminfoType::VMEMINFO_NR_UNRECLAIMABLE_PAGES, SYS_VMEMINFO_NR_UNRECLAIMABLE_PAGES_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZONE_ACTIVE_ANON, SYS_VMEMINFO_NR_ZONE_ACTIVE_ANON_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZONE_ACTIVE_FILE, SYS_VMEMINFO_NR_ZONE_ACTIVE_FILE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZONE_INACTIVE_ANON, SYS_VMEMINFO_NR_ZONE_INACTIVE_ANON_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZONE_INACTIVE_FILE, SYS_VMEMINFO_NR_ZONE_INACTIVE_FILE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZONE_UNEVICTABLE, SYS_VMEMINFO_NR_ZONE_UNEVICTABLE_DESC},
        {SysVMeminfoType::VMEMINFO_NR_ZONE_WRITE_PENDING, SYS_VMEMINFO_NR_ZONE_WRITE_PENDING_DESC},
        {SysVMeminfoType::VMEMINFO_OOM_KILL, SYS_VMEMINFO_OOM_KILL_DESC},
        {SysVMeminfoType::VMEMINFO_PGLAZYFREE, SYS_VMEMINFO_PGLAZYFREE_DESC},
        {SysVMeminfoType::VMEMINFO_PGLAZYFREED, SYS_VMEMINFO_PGLAZYFREED_DESC},
        {SysVMeminfoType::VMEMINFO_PGREFILL, SYS_VMEMINFO_PGREFILL_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_DIRECT, SYS_VMEMINFO_PGSCAN_DIRECT_DESC},
        {SysVMeminfoType::VMEMINFO_PGSCAN_KSWAPD, SYS_VMEMINFO_PGSCAN_KSWAPD_DESC},
        {SysVMeminfoType::VMEMINFO_PGSKIP_DMA, SYS_VMEMINFO_PGSKIP_DMA_DESC},
        {SysVMeminfoType::VMEMINFO_PGSKIP_MOVABLE, SYS_VMEMINFO_PGSKIP_MOVABLE_DESC},
        {SysVMeminfoType::VMEMINFO_PGSKIP_NORMAL, SYS_VMEMINFO_PGSKIP_NORMAL_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_DIRECT, SYS_VMEMINFO_PGSTEAL_DIRECT_DESC},
        {SysVMeminfoType::VMEMINFO_PGSTEAL_KSWAPD, SYS_VMEMINFO_PGSTEAL_KSWAPD_DESC},
        {SysVMeminfoType::VMEMINFO_SWAP_RA, SYS_VMEMINFO_SWAP_RA_DESC},
        {SysVMeminfoType::VMEMINFO_SWAP_RA_HIT, SYS_VMEMINFO_SWAP_RA_HIT_DESC},
        {SysVMeminfoType::VMEMINFO_WORKINGSET_RESTORE, SYS_VMEMINFO_WORKINGSET_RESTORE_DESC}};
}
void TraceStreamerConfig::InitSecurityMap()
{
    eventParserStatSeverityDescMap_ = {
        {
            TRACE_EVENT_BINDER_TRANSACTION,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BINDER_TRANSACTION_RECEIVED,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BINDER_TRANSACTION_ALLOC_BUF,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BINDER_TRANSACTION_LOCK,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BINDER_TRANSACTION_LOCKED,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BINDER_TRANSACTION_UNLOCK,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SCHED_SWITCH,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SCHED_BLOCKED_REASON,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_TASK_RENAME,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_TASK_NEWTASK,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_TRACING_MARK_WRITE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_PRINT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SCHED_WAKEUP,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SCHED_WAKING,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CPU_IDLE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CPU_FREQUENCY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CPU_FREQUENCY_LIMITS,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SUSPEND_RESUME,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_WORKQUEUE_EXECUTE_START,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_WORKQUEUE_EXECUTE_END,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLOCK_SET_RATE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLOCK_ENABLE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLOCK_DISABLE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLK_SET_RATE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLK_ENABLE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLK_DISABLE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_REGULATOR_SET_VOLTAGE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_REGULATOR_SET_VOLTAGE_COMPLETE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_REGULATOR_DISABLE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_REGULATOR_DISABLE_COMPLETE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_IPI_ENTRY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_IPI_EXIT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_IRQ_HANDLER_ENTRY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_IRQ_HANDLER_EXIT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SOFTIRQ_RAISE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SOFTIRQ_ENTRY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SOFTIRQ_EXIT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SCHED_WAKEUP_NEW,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_PROCESS_EXIT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_PROCESS_FREE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_CLOCK_SYNC,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SYS_ENTRY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_OOM_SCORE_ADJ_UPDATE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SYS_EXIT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_MEMORY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_HILOG,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_HIDUMP_FPS,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NATIVE_HOOK_MALLOC,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NATIVE_HOOK_FREE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NATIVE_HOOK_MMAP,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NATIVE_HOOK_MUNMAP,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NATIVE_HOOK_RECORD_STATISTICS,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NATIVE_HOOK_MEMTAG,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_SYS_MEMORY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_SYS_VIRTUAL_MEMORY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_DISKIO,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_PROCESS,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_CPU_USAGE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_NETWORK,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_JS_MEMORY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_PERF,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SIGNAL_GENERATE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_SIGNAL_DELIVER,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_BIO_BACKMERGE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_BIO_BOUNCE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_BIO_COMPLETE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_BIO_FRONTMERGE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_BIO_QUEUE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_BIO_REMAP,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_DIRTY_BUFFER,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_GETRQ,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_PLUG,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_RQ_COMPLETE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_RQ_INSERT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_RQ_REMAP,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_BLOCK_RQ_ISSUE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_EBPF,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_EBPF_FILE_SYSTEM,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_EBPF_PAGED_MEMORY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_EBPF_BIO_LATENCY,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_HISYSEVENT,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_SMAPS,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_ASHMEM,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_DMAMEM,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_GPU_PROCESS_MEM,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_GPU_WINDOW_MEM,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_VSYNC,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_ONVSYNC,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_FRAMEQUEUE,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
        {
            TRACE_EVENT_OTHER,
            {
                {STAT_EVENT_RECEIVED, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_DATA_LOST, STAT_SEVERITY_LEVEL_ERROR},
                {STAT_EVENT_NOTMATCH, STAT_SEVERITY_LEVEL_INFO},
                {STAT_EVENT_NOTSUPPORTED, STAT_SEVERITY_LEVEL_WARN},
                {STAT_EVENT_DATA_INVALID, STAT_SEVERITY_LEVEL_ERROR},
            },
        },
    };
}
} // namespace TraceCfg
} // namespace SysTuning
